/*
 * Copyright 2026-Present The Case Hub Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.casehub.generator;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import io.casehub.api.model.CaseDefinition;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

class ShorthandMigrationTest {

  private static JsonNode schema;
  private static JsonNode defs;

  @BeforeAll
  static void generateSchema() {
    schema = new CaseHubSchemaGenerator().generate(CaseDefinition.class);
    defs = schema.path("$defs");
  }

  private JsonNode resolveDef(JsonNode node) {
    if (node.has("$ref")) {
      String ref = node.get("$ref").asText();
      String defName = ref.replace("#/$defs/", "");
      return defs.path(defName);
    }
    return node;
  }

  @Nested
  class AdaptationShorthand {

    @Test
    void adaptationConfig_generatedAsDefByShorthandModule() {
      JsonNode adaptationDef = defs.path("AdaptationConfig");
      assertFalse(
          adaptationDef.isMissingNode(),
          "AdaptationConfig should exist in $defs (generated by ShorthandModule, not removed by UNWANTED_DEFS)");
      assertTrue(
          adaptationDef.has("oneOf"),
          "AdaptationConfig def should have oneOf (scalar-or-object shorthand)");
    }

    @Test
    void adaptationConfig_scalarVariantIsStringEnum() {
      JsonNode adaptationDef = defs.path("AdaptationConfig");
      JsonNode oneOf = adaptationDef.path("oneOf");
      JsonNode scalar = oneOf.get(0);
      assertEquals("string", scalar.path("type").asText());
      assertTrue(scalar.has("enum"), "scalar variant should have enum values");
      JsonNode enumValues = scalar.path("enum");
      assertEquals(4, enumValues.size());
      assertEquals("adaptive", enumValues.get(0).asText());
      assertEquals("conservative", enumValues.get(1).asText());
      assertEquals("off", enumValues.get(2).asText());
      assertEquals("progress", enumValues.get(3).asText());
    }

    @Test
    void adaptationConfig_objectVariantHasExpectedProperties() {
      JsonNode adaptationDef = defs.path("AdaptationConfig");
      JsonNode oneOf = adaptationDef.path("oneOf");
      JsonNode object = oneOf.get(1);
      assertEquals("object", object.path("type").asText());
      JsonNode props = object.path("properties");
      assertTrue(props.has("trigger"));
      assertTrue(props.has("optimization"));
      assertTrue(props.has("revision"));
      assertTrue(props.has("threshold"));
      assertTrue(props.has("metaReasoner"));
      assertTrue(props.has("repair"));
      assertTrue(props.has("contingencyThreshold"));
    }

    @Test
    void specAdaptationProperty_referencesAdaptationConfigDef() {
      JsonNode specProps = defs.path("CaseDefinitionSpec").path("properties");
      JsonNode adaptation = specProps.path("adaptation");
      assertFalse(adaptation.isMissingNode(), "spec should have 'adaptation' property");
      JsonNode resolved = resolveDef(adaptation);
      assertTrue(
          resolved.has("oneOf"), "adaptation property (resolved) should have oneOf structure");
    }
  }

  @Nested
  class ExpressionOrOverrideRedundancy {

    @Test
    void expressionOrOverride_existsInDefs() {
      JsonNode exprDef = defs.path("ExpressionOrOverride");
      assertFalse(exprDef.isMissingNode(), "ExpressionOrOverride should exist in $defs");
      assertTrue(exprDef.has("oneOf"), "ExpressionOrOverride should have oneOf (string or map)");
    }

    @Test
    void expressionOrOverride_scalarIsString() {
      JsonNode oneOf = defs.path("ExpressionOrOverride").path("oneOf");
      assertEquals("string", oneOf.get(0).path("type").asText());
    }

    @Test
    void expressionOrOverride_objectIsMapWithConstraints() {
      JsonNode oneOf = defs.path("ExpressionOrOverride").path("oneOf");
      JsonNode mapVariant = oneOf.get(1);
      assertEquals("object", mapVariant.path("type").asText());
      assertEquals(1, mapVariant.path("minProperties").asInt());
      assertEquals(1, mapVariant.path("maxProperties").asInt());
    }
  }

  @Nested
  class TriggerSubDefs {

    @Test
    void cloudEventTrigger_existsInDefs() {
      JsonNode cetDef = defs.path("CloudEventTrigger");
      assertFalse(cetDef.isMissingNode(), "CloudEventTrigger should exist in $defs");
    }

    @Test
    void cloudEventTrigger_hasShorthandOneOf() {
      JsonNode cetDef = defs.path("CloudEventTrigger");
      assertTrue(
          cetDef.has("oneOf"), "CloudEventTrigger should have oneOf (string or full object)");
      JsonNode oneOf = cetDef.path("oneOf");
      assertEquals("string", oneOf.get(0).path("type").asText());
      assertEquals("object", oneOf.get(1).path("type").asText());
    }

    @Test
    void scheduleTrigger_existsInDefs() {
      JsonNode stDef = defs.path("ScheduleTrigger");
      assertFalse(stDef.isMissingNode());
      assertTrue(stDef.has("oneOf"), "ScheduleTrigger should have cron/every oneOf");
    }

    @Test
    void contextChangeTrigger_existsInDefs() {
      JsonNode cctDef = defs.path("ContextChangeTrigger");
      assertFalse(cctDef.isMissingNode());
      assertEquals("object", cctDef.path("type").asText());
    }

    @Test
    void scopeActivatedTrigger_existsInDefs() {
      JsonNode satDef = defs.path("ScopeActivatedTrigger");
      assertFalse(satDef.isMissingNode());
      assertEquals("object", satDef.path("type").asText());
    }

    @Test
    void triggerDef_referencesSubDefs() {
      JsonNode triggerDef = defs.path("Trigger");
      assertFalse(triggerDef.isMissingNode());
      JsonNode props = triggerDef.path("properties");
      assertEquals("#/$defs/CloudEventTrigger", props.path("cloudEvent").path("$ref").asText());
      assertEquals("#/$defs/ScheduleTrigger", props.path("schedule").path("$ref").asText());
      assertEquals(
          "#/$defs/ContextChangeTrigger", props.path("contextChange").path("$ref").asText());
      assertEquals(
          "#/$defs/ScopeActivatedTrigger", props.path("scopeActivated").path("$ref").asText());
    }
  }
}
