quarkus.scheduler.start-mode=forced
quarkus.quartz.store-type=ram

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.index-dependency.engine.group-id=io.casehub
quarkus.index-dependency.engine.artifact-id=engine
quarkus.index-dependency.api.group-id=io.casehub
quarkus.index-dependency.api.artifact-id=api
