CREATE TABLE dead_letter_entry (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dead_letter_id  VARCHAR(255)  NOT NULL UNIQUE,
    case_id         UUID          NOT NULL,
    worker_id       VARCHAR(255)  NOT NULL,
    idempotency_hash VARCHAR(255),
    input_context   JSONB,
    retry_state     JSONB,
    status          VARCHAR(30)   NOT NULL,
    replay_attempts INTEGER       NOT NULL DEFAULT 0,
    arrived_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_replay_attempt_at TIMESTAMP WITH TIME ZONE,
    tenancy_id      VARCHAR(64)   NOT NULL
);

CREATE UNIQUE INDEX idx_dle_dead_letter_id ON dead_letter_entry (dead_letter_id);
CREATE INDEX idx_dle_case_id ON dead_letter_entry (case_id);
